### ISSUE TITLE
Provider - closing tasks for POC

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#176]
Remaining Tasks before PoC:
* [x] (@nieznanysprawiciel #167) provider agent payments
* [x] (@tworec) Fix market connection timeout while adding subscription (can not replicate, bug is not deterministic)
* [x] (@nieznanysprawiciel #185) Computing price based on usage counters from ExeUnit
    * [x] (@mfranciszkiewicz) Create wasmtime binary in which we could influence usage
    https://github.com/golemfactory/yagna/tree/helper/wasm-usage/exe-unit/apps/wasm-usage
* [x] (@tworec #175) loose task_package policy for Agents
* [x] (@nieznanysprawiciel) Pass real agreement to ExeUnit (#204)
* [x] (@Wiezzel #189) fix sort issue for invoice events and a workaround for long waiting schedule payment in `accept_invoice`
* [x] Tests on multiple providers

After PoC:
* [ ] #200 Provider agent to set activity status = `Terminated` when exeunit suddenly dies 
* [ ] (@nieznanysprawiciel) remove `CREDIT_ADDRESS` env from provider agent (use id)
* [x] (@tworec #152) Instruction for user (make it easy to use)
* [x] (@nieznanysprawiciel) ExeUnit's output should show up on provider's stdout (or log file)
* [x] (@mfranciszkiewicz #177 a part of #178) We need to guarantee that create_activity means ExeUnit is working and responsive
* [x] #149 Building deb package and running full flow from it
* [x] #147 Configuring tasks prices in provider (presets from agent CLI)
* [x] Remove previous_debit_note_id from NewDebitNote and provider logic related to updating ids (as discussed in https://github.com/golemfactory/yagna/pull/167#discussion_r401730466)

## Potential tasks to consider:
* [ ] Adjust coloring of ExeUnit logs to be similar to providers log.
* [ ] If ExeUnit fails (for example exe script command fails), it returns with exit code 0. Maybe it should return better error codes.
* [x] ~~ExeUnit should set usage vector at least one time before it exists. Otherwise provider can't issue invoice. Or maybe provider should handle this situation in better way?~~ Provider gets an option and computes cost assuming zero usage vector. (done in #185)
* [x] ExeUnit cache probably doesn't work correctly. I changed package hash, but ExeUnit deployed the same package as previously. (#202)
* [ ] Check strange behavior of cpu usage metric described here: #185
