### ISSUE TITLE
Activity API to handle edge cases

### ISSUE THREAD

**Issue by tworec** [golemfactory/yagna#178]
1. creation
   - [x] #177 wait for exeunit to start
   - [x] #183 activity API impl should monitor exeunit state (eg. check last `SetActivityUsage` is older than 10x set usage interval, than mark activity as inactive -- destroyed) if did not spawned within timeout or did not report usage within 10x interval we need to mark activity as inactive (eg. Send `DestroyEvent` to provider)
     (inactive means Terminated?) 
     (possibly it incur activity impl rewrite to be an actix actor -- need careful consideration) 

1. execution
   - [x] (@mfranciszkiewicz  #179 -> #184) we remove `TERMINATE` from ExeScript commands catalog, since we have `DestroyActivity` 
   - [x] (@mfranciszkiewicz  #180 -> #187) `Exec` returns `batch_id` and currently `GetExecBatchResults` returns partial results. `GetExecBatchResults` will have `timeout` param + command `index` within the batch. If both specified this call will block until command under given index will finish.

   - Not for PoC -- future improvement proposition: requestor activity API impl could collect all batch results from exeunit (a form of subscription) 

1. destruction
See above: TERMINATE is removed from exescripts

   - [x] #181 -> #190 
      - responsibility of provider agent is to:
         - spawn exeunit
         - terminate/kill exeunit exeunit
      - termination should be performed in two steps:
         - send SIGTERM/SIGINT
         - after grace period send SIGKILL
      - waiting `GetExecBatchResults` calls will receive some(?) GSB error
         - [ ] #182 make the local and net test for GSB

After PoC:
- [x] #191 handle gracefull shutdown internally within exeunit:
   - FLOW: `supervisor ---SIGINT---> runtime`
- [ ] #188 update activity-api.yaml to have full catalog of available ExeScript commands
