### ISSUE TITLE
Hybrid NET devnet observation

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2043]
Why:
We need to observe devnet to catch bugs that are hiding

What:
- [x] #2055
  - [x] Are checker tasks passing?
  - [x] Are there any execution errors, that don't break computation? (this problem occured -> https://github.com/golemfactory/yagna-triage/issues/103 )
- [x] Is tasks distribution between Nodes even?
- [x] Validate Offer propagation between Nodes
   - [x] After certain time, we should have all Offers collected on our Node
   - [x] We shouldn't overwhelm relay and network with broadcasts
   - [x] If we have Offers, how fast are Providers responding (or are they never responding)?
- [x] Get Offers timeout (-> https://github.com/golemfactory/yagna/issues/2053)
  - [x] Is this error happening often?
  - [x] Is it happening on the same Node whole time or on different Nodes?
 - [x] Check established connections
   - [x] Are we able to connect to relayed Nodes?
   - [x] Are pings reasonable low? (-> https://github.com/golemfactory/yagna/issues/2046)
 -~ [ ] #2064~
    - ~[ ] Are there any Nodes that are reconnecting very often?~
    - ~[ ] Are there Nodes, that are unable to pick up tasks?~
    - ~[ ] Connection errors or other problems~
