### ISSUE TITLE
Update goth runners

### ISSUE THREAD

**Issue by etam** [golemfactory/yagna#2436]
- [x] #2431 
- [x] add "goth" label to new runners
- [ ] update integration tests for ubuntu-22.04 compatibility https://github.com/golemfactory/yagna/issues/2456
- [ ] destroy old runners
