### ISSUE TITLE
[Tracking] Extend outbound testing

### ISSUE THREAD

**Issue by kamirr** [golemfactory/yagna#2543]
Goal: improve outbound testing

Test exploratively: try to break things via CLI, misbehaving tests, anything.

Consider different areas that can be broken, e.g.:
- [x] requestor POV: broken manifest, malformed properties, node.json
- [x] certificates validation
- [x] provider POV: CLI, rules configuration, incompatibility in interactions between keystore and rulestore
- [x] negotiations (handling of the protocol, validation)
- [x] exe-unit outbound implementation: malformed manifest
- [x] [certifiacate helper tool test](https://github.com/golemfactory/yagna/issues/2542)
