### ISSUE TITLE
Offer Demand Resolver

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#295]
### Scope
- [ ] incorporate existing resolver code to yagna repo: https://github.com/stranger80/golem-market-api
- [ ] Resolver is triggered upon Offer or Demand reception:
  - [ ] Subscribe Demand
  - [ ] Subscribe Offer
  - [ ] Broadcast Offer
  - [ ] Retrievie Offers
- [ ] Resover doesn't block execution. It only triggers matching. No awaiting.  
- [ ] new **Proposal**'s are emitted via EventsListeners from Matcher
- [ ] matching do not produce duplicated **Proposal**'s

### Task split
1. resolver with API: `resolve(offers: &Vec<Offer>, demands: &Vec<Demand>) -> Vec<Proposal>`
1. matecher-thread with two APIs:
   - `receive(ofde: OfferDemand)` with just id of an entity, which is stored in DB
   - `Sender<Proposal>` to put resulting Proposals
1. invocation of matcher-thread in four entrypoints specified above and pass `Receiver<Proposal>` to the negotiation engine

related to #232
